name: 'Callstack.ai Reviewer'
description: 'Run Callstack.ai reviewer'
branding:
  icon: 'play'
  color: 'gray-dark'
inputs:
  config:
    description: 'Config for reviewer'
    required: true
  head:
    description: 'Head commit sha'
    required: true
  openai_key:
    description: 'OpenAI key'
    required: false
    default: ''
  export:
    description: 'Save logs to artifact'
    required: false
  channel:
    description: 'Deployment channel (stable or pre-release)'
    required: false
    default: 'stable'
  tag:
    description: 'Docker image tag'
    required: false
    default: 'latest'

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.head }}

    - name: Set Docker image based on channel and tag
      shell: bash
      run: |
        if [[ "${{ inputs.channel }}" == "pre-release" ]]; then
          echo "DOCKER_IMAGE=callstackai/cal-staging:${{ inputs.tag }}" >> $GITHUB_ENV
        else
          echo "DOCKER_IMAGE=callstackai/cal:${{ inputs.tag }}" >> $GITHUB_ENV
        fi

    - name: Run reviewer without export
      if: ${{ !inputs.export }}
      uses: addnab/docker-run-action@v3
      env:
        OPENAI_KEY: ${{ inputs.openai_key }}
      with:
        image: ${{ env.DOCKER_IMAGE }}
        options: -v ${{ github.workspace }}:/code
        run: |
          /reviewer \
          --dir /code \
          --id ${{ github.run_id }} \
          --token ${{ github.token }} \
          --config "${{ inputs.config }}"

    - name: Run reviewer with export
      if: ${{ inputs.export }}
      uses: addnab/docker-run-action@v3
      env:
        OPENAI_KEY: ${{ inputs.openai_key }}
      with:
        image: ${{ env.DOCKER_IMAGE }}
        options: -v ${{ github.workspace }}:/code
        run: |
          /reviewer \
          --dir /code \
          --id ${{ github.run_id }} \
          --token ${{ github.token }} \
          --config "${{ inputs.config }}" \
          --export ${{ inputs.export }}
          
    - name: Export Chat logs
      uses: actions/upload-artifact@v4
      if: ${{ inputs.export }}
      with:
        name: chat-logs
        path: ${{ github.workspace }}/chats.json

    - name: Export logs
      uses: actions/upload-artifact@v4
      with:
        name: run-logs
        path: ${{ github.workspace }}/output.log
