name: 'Callstack.ai Reviewer'
description: 'Run Callstack.ai reviewer'
branding:
  icon: 'play'
  color: 'gray-dark'
inputs:
  config:
    description: 'Config for reviewer'
    required: true
  head:
    description: 'Head commit sha'
    required: true
  openai_key:
    description: 'OpenAI key'
    required: false
    default: ''
  export:
    description: 'Save logs to artifact'
    required: false
    default: false

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.head }}

    - name: Run reviewer
      uses: addnab/docker-run-action@v3
      env:
        OPENAI_KEY: ${{ inputs.openai_key }}
      with:
        image: callstackai/cal:latest
        options: -v ${{ github.workspace }}:/code
        run: |
          /reviewer \
          --dir /code \
          --id ${{ github.run_id }} \
          --token ${{ github.token }} \
          --config "${{ inputs.config }}" ${{ inputs.export && '--export' || null }}
          
    - name: Export logs
      uses: actions/upload-artifact@v4
      if: ${{ inputs.export }}
      with:
        name: chat-logs
        path: ${{ github.workspace }}/chats.json
